### PR TITLE
Enable testsuite on OSX

### PR DESCRIPTION
**Pull request by h-vetinari**
Follow-up to #1

### CODE REVIEW

**Comment by h-vetinari** [comment]
Copying from #1:
> OSX has a few failures - as far as I can tell from a quick look, all are due to `RuntimeError: Error on Node 0: Can't find class id in custom class type map`
> 
> ```
> =========================== short test summary info ============================
> FAILED tests/experimental/nn/ampnet_pipe_process/test_ampnet_pipe.py::test_async_event_loop_interleave_simple
> FAILED tests/experimental/nn/ampnet_pipe_process/test_ampnet_pipe.py::test_async_event_loop_interleave_hard
> FAILED tests/nn/pipe/test_balance.py::test_balance_by_time[cpu] - assert [3, ...
> FAILED tests/nn/pipe_process/test_pipe.py::test_parameters[AsyncPipe] - torch...
> FAILED tests/nn/pipe_process/test_pipe.py::test_sequential_like[AsyncPipe-balance0]
> FAILED tests/nn/pipe_process/test_pipe.py::test_sequential_like[AsyncPipe-balance1]
> FAILED tests/nn/pipe_process/test_pipe.py::test_balance_less_than_1[AsyncPipe]
> FAILED tests/nn/pipe_process/test_pipe.py::test_checkpoint_non_float_input[AsyncPipe]
> FAILED tests/nn/pipe_process/test_pipe.py::test_devices[AsyncPipe] - torch.mu...
> FAILED tests/nn/pipe_process/test_pipe.py::test_partitions[AsyncPipe] - torch...
> FAILED tests/nn/pipe_process/test_pipe.py::test_lazy_construction[AsyncPipe]
> FAILED tests/nn/pipe_process/test_pipe.py::test_missing_worker_map[AsyncPipe]
> FAILED tests/nn/pipe_process/test_pipe.py::test_async_event_loop - torch.mult...
> = 13 failed, 326 passed, 907 skipped, 5 xfailed, 66 warnings in 116.88s (0:01:56) =
> ```

@anj-s @blefaudeux any help with this is appreciated 🙃

**Comment by min-xu-ai** [comment]
Hi @h-vetinari, thanks for helping out with this. I think the full error log is like this:

```
2021-11-19T06:19:17.3337740Z E       torch.multiprocessing.spawn.ProcessRaisedException: 
2021-11-19T06:19:17.3338220Z E       
2021-11-19T06:19:17.3339270Z E       -- Process 1 terminated with the following error:
2021-11-19T06:19:17.3339910Z E       Traceback (most recent call last):
2021-11-19T06:19:17.3340960Z E         File "$PREFIX/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
2021-11-19T06:19:17.3341630Z E           fn(i, *args)
2021-11-19T06:19:17.3342750Z E         File "$PREFIX/lib/python3.7/site-packages/fairscale/utils/testing.py", line 220, in test_runner
2021-11-19T06:19:17.3343490Z E           test_func(rank, *args, **kwargs)
2021-11-19T06:19:17.3344530Z E         File "$PREFIX/lib/python3.7/site-packages/fairscale/utils/testing.py", line 249, in worker_process
2021-11-19T06:19:17.3345280Z E           if not dist_init(rank, world_size, filename, filename_rpc):
2021-11-19T06:19:17.3346610Z E         File "$PREFIX/lib/python3.7/site-packages/fairscale/utils/testing.py", line 179, in dist_init
2021-11-19T06:19:17.3347330Z E           rpc_backend_options=rpc.TensorPipeRpcBackendOptions(**tp_options),
2021-11-19T06:19:17.3348400Z E         File "$PREFIX/lib/python3.7/site-packages/torch/distributed/rpc/__init__.py", line 195, in init_rpc
2021-11-19T06:19:17.3349500Z E           _init_rpc_backend(backend, store, name, rank, world_size, rpc_backend_options)
2021-11-19T06:19:17.3350600Z E         File "$PREFIX/lib/python3.7/site-packages/torch/distributed/rpc/__init__.py", line 235, in _init_rpc_backend
2021-11-19T06:19:17.3351230Z E           rpc_backend_options=rpc_backend_options,
2021-11-19T06:19:17.3352250Z E         File "$PREFIX/lib/python3.7/site-packages/torch/distributed/rpc/backend_registry.py", line 106, in init_backend
2021-11-19T06:19:17.3352940Z E           return backend.value.init_backend_handler(*args, **kwargs)
2021-11-19T06:19:17.3354150Z E         File "$PREFIX/lib/python3.7/site-packages/torch/distributed/rpc/backend_registry.py", line 315, in _tensorpipe_init_backend_handler
2021-11-19T06:19:17.3354900Z E           api._all_gather(None, timeout=rpc_constants.DEFAULT_RPC_TIMEOUT_SEC)
2021-11-19T06:19:17.3355910Z E         File "$PREFIX/lib/python3.7/site-packages/torch/distributed/rpc/api.py", line 77, in wrapper
2021-11-19T06:19:17.3356510Z E           return func(*args, **kwargs)
2021-11-19T06:19:17.3357460Z E         File "$PREFIX/lib/python3.7/site-packages/torch/distributed/rpc/api.py", line 208, in _all_gather
2021-11-19T06:19:17.3358040Z E           timeout=timeout,
2021-11-19T06:19:17.3358960Z E         File "$PREFIX/lib/python3.7/site-packages/torch/distributed/rpc/api.py", line 77, in wrapper
2021-11-19T06:19:17.3359560Z E           return func(*args, **kwargs)
2021-11-19T06:19:17.3360500Z E         File "$PREFIX/lib/python3.7/site-packages/torch/distributed/rpc/api.py", line 765, in rpc_sync
2021-11-19T06:19:17.3361090Z E           return fut.wait()
2021-11-19T06:19:17.3361970Z E       RuntimeError: Error on Node 0: Can't find class id in custom class type map
```

It looks like something with rpc library of pytorch distributed on OSX. Perhaps we can skip those tests on on Mac osX. I think any code that uses rpc should be disabled.

**Comment by h-vetinari** [comment]
> It looks like something with rpc library of pytorch distributed on OSX. Perhaps we can skip those tests on on Mac osX. I think any code that uses rpc should be disabled.

As I mentioned in my [comment](https://github.com/facebookresearch/fairscale/pull/863#issuecomment-974564487) on the other fairscale-PR, pytorch builds are a bit tricky for conda-forge at the moment. So it's possible that the rpc stuff is not working correctly (or using a different version). I'd be happy to get to the bottom of this over time, but for the moment we could also disable these test.

CC @conda-forge/pytorch-cpu for viz, if someone has an idea about what might be going wrong with rpc on osx.

**Comment by h-vetinari** [comment]
@min-xu-ai 
This is starting to look _much_ better. Python 3.9 passed completely, and Python 3.8 / 3.10 had a single failure: 
```
=========================== short test summary info ============================
FAILED tests/nn/pipe/test_balance.py::test_balance_by_time[cpu] - assert [5, 1] == [4, 2]
  At index 0 diff: 5 != 4
  Full diff:
  - [4, 2]
  + [5, 1]
= 1 failed, 428 passed, 881 skipped, 5 xfailed, 72 warnings in 310.47s (0:05:10) =
```

I guess we could skip that test?

From the name `test_balance_by_time`, it seems like it might be susceptible to various hardware fluctuations or race conditions etc.

**Comment by min-xu-ai** [comment]
Yes. Please skip.

**Pull request merged**
