### PR TITLE
Enable test suite (currently linux-only)

### PR DESCRIPTION
**Pull request by h-vetinari**
Something that was tricky in the staged-recipes PR.

### CODE REVIEW

**Comment by h-vetinari** [comment]
It seems even the non-cuda test suite fails on the absence of a GPU?
```
E         File "$PREFIX/lib/python3.9/site-packages/torch/distributed/rpc/backend_registry.py", line 211, in _tensorpipe_exchange_and_check_all_device_maps
E           raise ValueError(
E       ValueError: Node worker0 has source devices with invalid indices in its device map for worker1
E       device map = {device(type='cuda', index=0): device(type='cuda', index=1)}
E       device count = 0
```

**Comment by blefaudeux** [comment]
> It seems even the non-cuda test suite fails on the absence of a GPU?
> 
> ```
> E         File "$PREFIX/lib/python3.9/site-packages/torch/distributed/rpc/backend_registry.py", line 211, in _tensorpipe_exchange_and_check_all_device_maps
> E           raise ValueError(
> E       ValueError: Node worker0 has source devices with invalid indices in its device map for worker1
> E       device map = {device(type='cuda', index=0): device(type='cuda', index=1)}
> E       device count = 0
> ```

(I'm only loosely attached to fairscale these days, cc @anj-s for a more up to date perspective) It's very possible that most of fairscale is not very useful without a GPU indeed, and that as a consequence most tests do require one.

**Comment by h-vetinari** [comment]
> It's very possible that most of fairscale is not very useful without a GPU indeed, and that as a consequence most tests do require one.

Thanks for chiming in! In that case, I need to wonder if a CPU-only package of fairscale even makes sense? I mean, yes, I can skip GPU specific tests, but that's a game of whack-a-mole that's not fun to play.

Have you considered using the new [python-wrappers](https://nvidia.github.io/cuda-python/overview.html) for cuda from NVIDIA that recently reached general availability? This would presumably be an excellent tool to use to determine dynamically whether the GPU can actually be used.

@anj-s, what would you think about adding a check (possibly conditional on its availability) that the GPU tests are only run in the drivers & GPU can be found?

**Comment by h-vetinari** [comment]
Alrighty! This is starting to look much better! :)

Linux passes, OSX has a few failures - as far as I can tell from a quick look, all are due to `RuntimeError: Error on Node 0: Can't find class id in custom class type map`

**Comment by h-vetinari** [comment]
To move on with #2, I'm going to merge this now without testing osx (which is not great but builds have already been published anyway), and will open another PR afterwards.

**Comment by h-vetinari** [comment]
> Thank you for the pointer to the wrapper! Is it somehow different than using PyTorch's `torch.cuda.is_available`?

Sorry, I don't know the difference, but my suspicion is that the `cuda-python` one goes deeper (and is therefore probably more accurate), as it's built by NVIDIA itself.

> From what I understand, we skip tests if GPUs are not available at least on circleCI. Are you seeing something different?

The comment you were responding to was already outdated; after the release of 0.4.3 (#4), I rebased this feedstock and the test suite passed on linux. After merging this PR, I then rebased #2, which _also_ passed the test suite (despite not having GPU hardware). I'm quite happy with that, but you're more than welcome to download the GPU artefacts from conda-forge and report back if anything isn't working as intended. 🙃

**Pull request merged**
